AB-2545- Add User Rust SDK
absmach/supermq-sdk-rust pull request #1
Opened 2024-12-11 13:38 UTC by dorcaslitunya

# What type of PR is this?

This is a feature because it adds the following functionality:  Adding a Rust SDK to supreme
.

## What does this do?

- Adds a User SDK to supreme

## Which issue(s) does this PR fix/relate to?

- Related Issue #2545

## Have you included tests for your changes?

No, I have not included tests because its a draft PR.

## Did you document any new/modified features?

No, I have not updated the documentation because its a draft PR.

2024-12-24 09:58 UTC, dborovcanin requested changes
This is way to many generated files for relatively simple SDK. Please:
- Clean up the generated files and try to reduce the amount of generated files.
- Remove useless Markdown docs.
- Do not generate package per MG service - check how it's done in the Go SDK.
- Update README with meaningfull instructions on how to use SDK, install tool that's used to generate it and how to use the tool with existing SuperMQ repo.
- Update examples to make some use of it (i.e. registrer, login, create domain, group, client, channel, connect them, send an HTTP message).

2025-01-12 01:34 UTC, drasko requested changes

2025-01-12 01:34 UTC, drasko commented on bootstrap/.gitignore
Bootstrap is removed from SuperMQ, so please take care to include only services in SuperMQ. Change and correct OpenAPI files if needed.

2025-01-12 23:09 UTC, dorcaslitunya commented
I have refactored the code as suggested. Please let me know if this works or any further improvements to it.

I just need to improve examples. 

@drasko @dborovcanin

2025-01-12 23:10 UTC, dorcaslitunya commented on bootstrap/.gitignore
I have deleted all files pertaining to Bootstrap

2025-01-17 07:11 UTC, dborovcanin reviewed
Can we group structs related to a service in a single file? Kinda like what we do in the YAML files?

2025-01-29 11:04 UTC, dborovcanin commented
@dorcaslitunya Can you, please, address the pending comment?

2025-01-29 12:52 UTC, dorcaslitunya commented
Hi @dborovcanin 

Will address this from Friday

2025-09-09 08:23 UTC, merged